import type { Insight } from "../lib/types";

export default function InsightPanel({
  insight,
  backend,
}: {
  insight: Insight;
  backend: string;
}) {
  const isClaude = backend.startsWith("claude");
  return (
    <div className="card flex h-full flex-col p-5">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2 text-sm font-semibold text-brand">
          <span>✦</span> AI Insight
        </div>
        <span
          className="badge bg-edge text-slate-400"
          title={`Generated by ${insight.generated_by}`}
        >
          {isClaude ? "Claude" : "Mock (no API key)"}
        </span>
      </div>

      <div className="text-lg font-semibold leading-snug">{insight.headline}</div>
      <p className="mt-2 text-sm text-slate-300">{insight.narrative}</p>

      <Group title="Key findings" items={insight.key_findings} tone="text-slate-200" />
      <Group title="Risks" items={insight.risks} tone="text-bad" bullet="▲" />
      <Group
        title="Recommended actions"
        items={insight.recommended_actions}
        tone="text-good"
        bullet="→"
      />

      <div className="mt-auto pt-4 text-[11px] text-slate-500">
        Grounded strictly in the dashboard data. Source: {insight.generated_by}
      </div>
    </div>
  );
}

function Group({
  title,
  items,
  tone,
  bullet = "•",
}: {
  title: string;
  items: string[];
  tone: string;
  bullet?: string;
}) {
  if (!items?.length) return null;
  return (
    <div className="mt-4">
      <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-500">
        {title}
      </div>
      <ul className="space-y-1">
        {items.map((it, i) => (
          <li key={i} className={`flex gap-2 text-sm ${tone}`}>
            <span className="select-none opacity-70">{bullet}</span>
            <span className="text-slate-300">{it}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
